XBotCore:
  config_path: "configs/ADVR_shared/configs/cogimon.yaml"

XBotInterface:
  urdf_path: "configs/ADVR_shared/urdf/cogimon.urdf"    
  srdf_path: "configs/ADVR_shared/srdf/cogimon.srdf"
  joint_map_path: "configs/ADVR_shared/joint_map/cogimon_joint_map.yaml"

RobotInterface:
  framework_name: "ROS"

ModelInterface:
  model_type: "RBDL"
  is_model_floating_base: "true"
  
MasterCommunicationInterface:
  framework_name: "ROS"

XBotRTPlugins:
  plugins: ["HomingExample","chengxu_walking"] #simpleIK""#, "HokuyoRotation", "chengxu_walking", "IkRosSMPub", "Grasp"] #, "chengxu_walking" "XBotRTCommunication"] 
  io_plugins: []
  
NRTPlugins:
  plugins: [] 
  
TransmissionPlugins:
  plugins: [] #CogimonImpedanceAnkles CogimonAnkles
  
WebServer:
  enable: "false"
  address: "10.24.5.100"
  port: "8081"

SimulationOptions:
  verbose_mode: "true"

