XBotCore:
  config_path: "configs/CogimonConfig/configs/cogimon_francescox.yaml"  #/home/embedded/jiatao_catkin_ws/src/multi_strategy_walking/configs/CogimonConfig/configs/cogimon_francescox.yaml
  

XBotInterface:
   urdf_path: "configs/CogimonConfig/urdf/cogimon.urdf"
   srdf_path: "configs/CogimonConfig/srdf/cogimon.srdf"
  #"/home/embedded/jiatao_catkin_ws/src/multi_strategy_walking/configs/CogimonConfig/urdf/cogimon.urdf"
  #"/home/embedded/jiatao_catkin_ws/src/multi_strategy_walking/configs/CogimonConfig/srdf/cogimon.srdf"
  joint_map_path: "configs/CogimonConfig/joint_map/cogimon_joint_map.yaml"

RobotInterface:
  framework_name: "ROS"

ModelInterface:
  model_type: "RBDL"
  is_model_floating_base: "true"
  
MasterCommunicationInterface:
  framework_name: "ROS"

XBotRTPlugins:
  plugins: ["HomingExample", "multi_strategy_walking"]  #,"multi_strategy_walking" 
  io_plugins: []
  
NRTPlugins:
  plugins: [] 
  
TransmissionPlugins:
  plugins: [] #CogimonImpedanceAnkles CogimonAnkles
  
WebServer:
  enable: "true"
  address: "127.0.0.1"
  port: "8081"

SimulationOptions:
  verbose_mode: "true"



